Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: Please enter VPC CIDR

  SubnetCIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: Please enter CIDR for Subnet

Resources:
  myVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-5rr7872wyfmu-us-east-1/2022-12-14T120449.645Zckq-vpc.yaml
      Parameters:
        VpcCIDR:
          Ref: VpcCIDR
        SubnetCIDR: 
          Ref: SubnetCIDR

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      KeyName: 
        Ref: SSHKey
      NetworkInterfaces:
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        SubnetId: !GetAtt myVPCStack.Outputs.mySubnet
      # we install our web server with user data
      UserData: 
        Fn::Base64: |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World from user data" > /var/www/html/index.html


Outputs:
  AppURL:
    Description: Application URL to access
    Value: !Sub 'http://${MyInstance.PublicDnsName}:8080/index.html' 